routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);
Route::get('/logout', [
    'uses' => 'App\Http\Controllers\Auth\LoginController@logout',
    'as' => 'logout',
]);
Route::get('/notifications/{notification}/read', 'App\Http\Controllers\NotificationController@markAsRead')->name('notifications.read');

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix' => 'backsite', 'namespace' => 'App\Http\Controllers', 'middleware' => 'auth', 'as' => 'backsite.' ], function () {
    // Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    // Route::get('/home', [
    //     'uses' => 'HomeController@index',
    //     'as' => 'backsite.beranda.index',
    // ]);

    Route::resource('dashboard', 'HomeController');

    Route::resource('project', 'ProjectController');
    Route::resource('user', 'UserController');
    Route::resource('task', 'TaskController');


    Route::group(['prefix' => 'datatable', 'as' => 'dtable.'], function () {
        Route::get('/project', [
            'uses' => 'ProjectController@datatable',
            'as' => 'project',
        ]);

        Route::get('/task', [
            'uses' => 'TaskController@datatable',
            'as' => 'task',
        ]);

        Route::get('/user', [
            'uses' => 'UserController@datatable',
            'as' => 'user',
        ]);
    });
});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'description',
        'progress',
        'status'
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function tasks() {
        return $this->hasMany(Task::class);
    }

    public function calculateProgress()
    {
        $tasks = $this->tasks;
        if ($tasks->isEmpty()) {
            return 0;
        }

        $totalProgress = $tasks->sum(function ($task) {
            return floatval(rtrim($task->progress, '%'));
        });

        return $totalProgress / $tasks->count();
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Project;
use App\Models\Task;
use RealRashid\SweetAlert\Facades\Alert;

class ProjectController extends Controller
{
    public function index()
    {
        if (!empty(session('error_msg')))
            Alert::error('Failed !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        return view('projects.index');
    }

    public function datatable(Request $request) {
        $model = Project::query();

        $dTable = DataTables()->of($model)
        ->addIndexColumn()
        ->editColumn('created_at', function ($project) {
            return $project->created_at ? $project->created_at->format('d/M/Y') : '';
        });

        return $dTable->toJson();
    }

    public function create()
    {
        return view('projects.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required',
            // 'progress' => 'required|numeric|min:0|max:100',
            // 'status' => 'required'
        ]);

        try {
            $p = new Project();
            $p->user_id = auth()->id();
            $p->title = $request->title;
            $p->description = $request->description;
            $p->progress = 0;
            $p->status = $request->has('status') ? 'Active' : 'Inactive';
            $p->save();

        } catch (\Exception $e) {
            return redirect()->route('backsite.project.index')->with('error_msg', 'Create Project failed.');
        }
        return redirect()->route('backsite.project.index')->with('success', 'Project created successfully.');
    }

    public function show(Project $project)
    {
        $taskCounts = Task::selectRaw('status, COUNT(*) as count')
                    ->where('project_id', $project->id)
                    ->groupBy('status')
                    ->pluck('count', 'status');

        return view('projects.show', ['taskCounts' => $taskCounts]);
    }

    public function edit(Project $project)
    {
        return view('projects.edit', ['project' => $project]);
    }

    public function update(Request $request, Project $project)
    {
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required',
            // 'progress' => 'required|numeric|min:0|max:100',
            // 'status' => 'required'
        ]);

        try {
            $p = Project::find($project->id);
            $p->user_id = auth()->id();
            $p->title = $request->title;
            $p->description = $request->description;
            $p->progress = $project->calculateProgress();
            $p->status = $request->has('status') ? 'Active' : 'Inactive';
            $p->save();

        } catch (\Exception $e) {
            return redirect()->route('backsite.project.index')->with('error_msg', 'Update Project failed.');
        }
        return redirect()->route('backsite.project.index')->with('success', 'Project updated successfully.');
    }

    public function destroy(Project $project)
    {
        try {
            $project->delete();

        } catch (\Exception $e) {
            return redirect()->route('backsite.project.index')->with('error_msg', 'Delete Project failed.');
        }
        return redirect()->route('backsite.project.index')->with('success', 'Project deleted successfully.');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app-master')
@section('menuProject', 'active')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" action="{{ route('backsite.project.store') }}" class="form-horizontal">
                        @csrf
                        <div class="card-header card-header-text" data-background-color="rose">
                            <h4 class="card-title">Create Project</h4>
                        </div>
                        <div class="card-content">
                            <div class="row">
                                <label class="col-sm-2 label-on-left">Title</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <label class="control-label"></label>
                                        <input type="text" class="form-control" name="title" placeholder="Title">
                                        <!-- <span class="help-block">A block of help text that breaks onto a new line.</span> -->
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Description</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <label class="control-label"></label>
                                        <textarea class="form-control" placeholder="Description" name="description"></textarea>
                                        <!-- <span class="help-block">A block of help text that breaks onto a new line.</span> -->
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Status</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="status"> Active ?
                                            </label>
                                        </div>
                                        <!-- <span class="help-block">A block of help text that breaks onto a new line.</span> -->
                                    </div>
                                </div>
                            </div>
                            
                            
                            <div class="row">
                                <div class="col-sm-2">
                                    <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app-master')
@section('menuProject', 'active')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" action="{{ route('backsite.project.update', $project->id) }}" class="form-horizontal">
                        @method('PUT')
                        @csrf
                        <div class="card-header card-header-text" data-background-color="rose">
                            <h4 class="card-title">Update Project {{ $project->title }}</h4>
                        </div>
                        <div class="card-content">
                            <div class="row">
                                <label class="col-sm-2 label-on-left">Title</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <label class="control-label"></label>
                                        <input type="text" class="form-control" name="title" placeholder="Title" value="{{ $project->title }}">
                                        <!-- <span class="help-block">A block of help text that breaks onto a new line.</span> -->
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Description</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <label class="control-label"></label>
                                        <textarea class="form-control" placeholder="Description" name="description">{{ $project->description }}</textarea>
                                        <!-- <span class="help-block">A block of help text that breaks onto a new line.</span> -->
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Status</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="status" {{ $project->status == 'active' ? 'checked' : '' }}> Active ?
                                            </label>
                                        </div>
                                        <!-- <span class="help-block">A block of help text that breaks onto a new line.</span> -->
                                    </div>
                                </div>
                            </div>
                            
                            
                            <div class="row">
                                <div class="col-sm-2">
                                    <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app-master')
@section('menuProject', 'active')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <a href="{{ route('backsite.project.create') }}" class="card-header card-header-icon" data-background-color="purple">
                        <i class="material-icons">add</i>
                    </a>
                    <div class="card-content">
                        <h4 class="card-title">Projects</h4>
                        <div class="toolbar">
                            <!--        Here you can write extra buttons/actions for the toolbar              -->
                        </div>
                        <div class="material-datatables">
                            <table id="dtable" class="dtable table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Project Name</th>
                                        <th>Description</th>
                                        <th>Created At</th>
                                        <th>Status</th>
                                        <th class="disabled-sorting text-right" width="25%">Actions</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>No</th>
                                        <th>Project Name</th>
                                        <th>Description</th>
                                        <th>Created At</th>
                                        <th>Status</th>
                                        <th class="disabled-sorting text-right">Actions</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- end content-->
                </div>
                <!--  end card  -->
            </div>
            <!-- end col-md-12 -->
        </div>
        <!-- end row -->
    </div>
</div>
@endsection

@section('script')
    <script>


        getDatatable()

function getDatatable() {
    /*Datatable*/
    $('.dtable').DataTable().destroy();
    $('.dtable').DataTable({
        serverSide: true,
        processing: true,
        lengthChange: false,
        ajax: {
            type: 'GET',
            url: "{{ route('backsite.dtable.project') }}",
            data: {
                _token: "{{ csrf_token() }}",
            }
        },
        columns: [{
                data: 'DT_RowIndex',
                name: 'DT_RowIndex',
                orderable: false,
                searchable: false
            },
            {
                data: 'title',
                name: 'title'
            },
            {
                data: 'description',
                name: 'description'
            },
            {
                data: 'created_at',
                name: 'created_at'
            },
            {
                data: 'status',
                name: 'status'
            },
            {
                data: 'action',
                name: 'action',
                orderable: false,
                searchable: false,
                render: function(data, type, row) {
                    
                    let url = route('backsite.task.show', {
                        id: row.id,
                    });
                    url += '?type=todo';

                    return ` 
                        <form action="${route('backsite.project.destroy', {
                            id: row.id,
                        })}" method="POST" id="form_${row.id}">
                            @csrf
                            <input type="hidden" name="_method" value="delete">
                            <input type="hidden" name="role_ref" value="{{ request()->query('role') }}">
                            <a type="button" rel="tooltip" class="btn btn-sm btn-success btn-round" data-original-title="" title="" href="${route('backsite.project.edit', {
                                id: row.id
                            })}">
                                <i class="material-icons">edit</i>
                            </a>
                            

                            <a type="button" rel="tooltip" class="btn btn-sm btn-warning btn-round" data-original-title="" title="" href="${url}">
                                <i class="material-icons">list</i>
                            </a>

                            <a type="button" rel="tooltip" class="btn btn-sm btn-info btn-round" data-original-title="" title="" href="${route('backsite.project.show', {
                                id: row.id,
                            })}">
                                <i class="material-icons">bar_chart</i>
                            </a>

                            <button type="submit" rel="tooltip" class="btn btn-sm btn-danger btn-round btn_delete" id="${row.id}" data-original-title="" title="">
                                <i class="material-icons">delete</i>
                            </button>
                        </form>
                        `
                }
            },
        ]
    })
}

$(document).on('click', '.btn_delete', function(e) {
    e.preventDefault()

    Swal.fire({
        icon: 'warning',
        title: 'Are You Sure ?',
        text: "Are you sure to delete this item!",
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it !'
    }).then((result) => {
        if (result.isConfirmed) {
            let id = $(this).attr('id')
            $("#form_" + id).submit()
        }
    });
})
    </script>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app-master')

@section('menuProject', 'active')

@section('style')
<style>
.card-content {
    width: 40%;
    height: 40%;
}
</style>
@endsection

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-text" data-background-color="rose">
                        <h4 class="card-title">Project Stats (Task Status Distribution)</h4>
                    </div>
                    <div class="card-content">
                        <canvas id="statusChart" width="200" height="200"></canvas>
                        <div class="chart-notes">
                            <p><strong>Note:</strong> This chart displays the distribution of tasks across different statuses within the project. Each color represents a different status as follows:</p>
                            <ul>
                                <li><span style="color: rgba(255, 99, 132, 0.5);">●</span> Todo</li>
                                <li><span style="color: rgba(54, 162, 235, 0.5);">●</span> Onprogress</li>
                                <li><span style="color: rgba(255, 206, 86, 0.5);">●</span> Done</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
document.addEventListener('DOMContentLoaded', function () {
    var ctx = document.getElementById('statusChart').getContext('2d');
    var statusChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: @json($taskCounts->keys()),
            datasets: [{
                label: 'Task Distribution',
                data: @json($taskCounts->values()),
                backgroundColor: [
                    'rgba(255, 99, 132, 0.5)',
                    'rgba(54, 162, 235, 0.5)',
                    'rgba(255, 206, 86, 0.5)',
                    'rgba(75, 192, 192, 0.5)',
                    'rgba(153, 102, 255, 0.5)',
                    'rgba(255, 159, 64, 0.5)'
                ],
                borderColor: [
                    'rgba(255, 255, 255, 1)',
                    'rgba(255, 255, 255, 1)',
                    'rgba(255, 255, 255, 1)',
                    'rgba(255, 255, 255, 1)',
                    'rgba(255, 255, 255, 1)',
                    'rgba(255, 255, 255, 1)'
                ],
                borderWidth: 2
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: {
                    position: 'top',
                }
            }
        }
    });
});
</script>
@endsection