routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);
Route::get('/logout', [
    'uses' => 'App\Http\Controllers\Auth\LoginController@logout',
    'as' => 'logout',
]);
Route::get('/notifications/{notification}/read', 'App\Http\Controllers\NotificationController@markAsRead')->name('notifications.read');

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix' => 'backsite', 'namespace' => 'App\Http\Controllers', 'middleware' => 'auth', 'as' => 'backsite.' ], function () {
    // Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    // Route::get('/home', [
    //     'uses' => 'HomeController@index',
    //     'as' => 'backsite.beranda.index',
    // ]);

    Route::resource('dashboard', 'HomeController');

    Route::resource('project', 'ProjectController');
    Route::resource('user', 'UserController');
    Route::resource('task', 'TaskController');


    Route::group(['prefix' => 'datatable', 'as' => 'dtable.'], function () {
        Route::get('/project', [
            'uses' => 'ProjectController@datatable',
            'as' => 'project',
        ]);

        Route::get('/task', [
            'uses' => 'TaskController@datatable',
            'as' => 'task',
        ]);

        Route::get('/user', [
            'uses' => 'UserController@datatable',
            'as' => 'user',
        ]);
    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    public function projects() {
        return $this->hasMany(Project::class);
    }

    public function tasks() {
        return $this->hasManyThrough(Task::class, Project::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class UserController extends Controller
{
    //
    public function index()
    {
        if (!empty(session('error_msg')))
            Alert::error('Failed !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        return view('users.index');
    }

    public function datatable() {
        $model = User::where('id', '!=', auth()->id());

        $dTable = DataTables()->of($model)
        ->addIndexColumn()
        ->editColumn('created_at', function ($user) {
            return $user->created_at ? $user->created_at->format('d/M/Y') : '';
        });

        return $dTable->toJson();
    }

    public function create()
    {
        return view('users.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|min:6',
        ]);

        try {
            $user = User::create([
                'name' => $request->name,
                'email' => $request->email,
                'password' => bcrypt($request->password),
            ]);
            $user->sendEmailVerificationNotification();

        } catch (\Exception $e) {
            return redirect()->route('backsite.user.index')->with('error_msg', 'Create User failed.');
        }

        return redirect()->route('backsite.user.index')->with('success', 'User created successfully.');
    }

    public function show(User $user)
    {
        return view('users.show', ['user' => $user]);
    }

    public function edit(User $user)
    {
        return view('users.edit', ['user' => $user]);
    }

    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email|unique:users,email,' . $user->id,
            'password' => 'nullable|min:6',
        ]);

        try {
            $user->update([
                'name' => $request->name,
                'email' => $request->email,
                'password' => $request->filled('password') ? bcrypt($request->password) : $user->password,
            ]);
        } catch (\Exception $e) {
            return redirect()->route('backsite.user.index')->with('error_msg', 'Update User failed.');
        }

        return redirect()->route('backsite.user.index')->with('success', 'User updated successfully.');
    }

    public function destroy(User $user)
    {
        try {
            $user->delete();

        } catch (\Exception $e) {
            return redirect()->route('backsite.user.index')->with('error_msg', 'Delete User failed.');
        }
        return redirect()->route('backsite.user.index')->with('success', 'User deleted successfully.');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app-master')

@section('menuUser', 'active')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" action="{{ route('backsite.user.store') }}" class="form-horizontal">
                        @csrf
                        <div class="card-header card-header-text" data-background-color="rose">
                            <h4 class="card-title">Create User</h4>
                        </div>
                        <div class="card-content">
                            <!-- Name Input -->
                            <div class="row">
                                <label class="col-sm-2 label-on-left">Name</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <input type="text" class="form-control" name="name" placeholder="Name" required>
                                        @if ($errors->has('name'))
                                            <span class="block" style="color: red;">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <!-- Email Input -->
                            <div class="row">
                                <label class="col-sm-2 label-on-left">Email</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <input type="email" class="form-control" name="email" placeholder="Email" required>
                                        @if ($errors->has('email'))
                                            <span class="block" style="color: red;">
                                                <strong>{{ $errors->first('email') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <!-- Password Input -->
                            <div class="row">
                                <label class="col-sm-2 label-on-left">Password</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <input type="password" class="form-control" name="password" placeholder="Password" required>
                                        @if ($errors->has('password'))
                                            <span class="block" style="color: red;">
                                                <strong>{{ $errors->first('password') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <!-- Submit Button -->
                            <div class="row">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-fill btn-rose">Create User</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app-master')

@section('menuUser', 'active')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" action="{{ route('backsite.user.update', $user->id) }}" class="form-horizontal">
                        @method('PUT')
                        @csrf
                        <div class="card-header card-header-text" data-background-color="rose">
                            <h4 class="card-title">Update User {{ $user->name }}</h4>
                        </div>
                        <div class="card-content">
                            <!-- Name Input -->
                            <div class="row">
                                <label class="col-sm-2 label-on-left">Name</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <input type="text" class="form-control" name="name" placeholder="Name" value="{{ $user->name }}" required>
                                        @if ($errors->has('name'))
                                            <span class="block" style="color: red;">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <!-- Email Input -->
                            <div class="row">
                                <label class="col-sm-2 label-on-left">Email</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <input type="email" class="form-control" name="email" placeholder="Email" value="{{ $user->email }}" required>
                                        @if ($errors->has('email'))
                                            <span class="block" style="color: red;">
                                                <strong>{{ $errors->first('email') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <!-- Password Input -->
                            <div class="row">
                                <label class="col-sm-2 label-on-left">Password</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating is-empty">
                                        <input type="password" class="form-control" name="password" placeholder="Password">
                                        @if ($errors->has('password'))
                                            <span class="block" style="color: red;">
                                                <strong>{{ $errors->first('password') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <!-- Submit Button -->
                            <div class="row">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-fill btn-rose">Create User</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app-master')
@section('menuUser', 'active')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <a href="{{ route('backsite.user.create') }}" class="card-header card-header-icon" data-background-color="purple">
                        <i class="material-icons">add</i>
                    </a>
                    <div class="card-content">
                        <h4 class="card-title">Users</h4>
                        <div class="toolbar">
                            <!--        Here you can write extra buttons/actions for the toolbar              -->
                        </div>
                        <div class="material-datatables">
                            <table id="dtable" class="dtable table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Created At</th>
                                        <th class="disabled-sorting text-right">Actions</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Created At</th>
                                        <th class="disabled-sorting text-right">Actions</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- end content-->
                </div>
                <!--  end card  -->
            </div>
            <!-- end col-md-12 -->
        </div>
        <!-- end row -->
    </div>
</div>
@endsection

@section('script')
<script>
    getDatatable()

    function getDatatable() {
        /*Datatable*/
        $('.dtable').DataTable().destroy();
        $('.dtable').DataTable({
            serverSide: true,
            processing: true,
            lengthChange: false,
            ajax: {
                type: 'GET',
                url: "{{ route('backsite.dtable.user') }}",
                data: {
                    _token: "{{ csrf_token() }}",
                }
            },
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'email',
                    name: 'email'
                },
                {
                    data: 'created_at',
                    name: 'created_at'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false,
                    render: function(data, type, row) {
                        return ` 
                        <form action="${route('backsite.user.destroy', {
                            id: row.id,
                        })}" method="POST" id="form_${row.id}">
                            @csrf
                            <input type="hidden" name="_method" value="delete">
                            <input type="hidden" name="role_ref" value="{{ request()->query('role') }}">
                            <a type="button" rel="tooltip" class="btn btn-sm btn-success btn-round" data-original-title="" title="" href="${route('backsite.user.edit', {
                                id: row.id
                            })}">
                                <i class="material-icons">edit</i>
                            </a>
                            <button type="submit" rel="tooltip" class="btn btn-sm btn-danger btn-round btn_delete" id="${row.id}" data-original-title="" title="">
                                <i class="material-icons">delete</i>
                            </button>
                        </form>
                        `
                    }
                },
            ]
        })
    }

    $(document).on('click', '.btn_delete', function(e) {
        e.preventDefault()

        Swal.fire({
            icon: 'warning',
            title: 'Are You Sure ?',
            text: "Are you sure to delete this item!",
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it !'
        }).then((result) => {
            if (result.isConfirmed) {
                let id = $(this).attr('id')
                $("#form_" + id).submit()
            }
        });
    })
</script>
@endsection