routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);
Route::get('/logout', [
    'uses' => 'App\Http\Controllers\Auth\LoginController@logout',
    'as' => 'logout',
]);
Route::get('/notifications/{notification}/read', 'App\Http\Controllers\NotificationController@markAsRead')->name('notifications.read');

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix' => 'backsite', 'namespace' => 'App\Http\Controllers', 'middleware' => 'auth', 'as' => 'backsite.' ], function () {
    // Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    // Route::get('/home', [
    //     'uses' => 'HomeController@index',
    //     'as' => 'backsite.beranda.index',
    // ]);

    Route::resource('dashboard', 'HomeController');

    Route::resource('project', 'ProjectController');
    Route::resource('user', 'UserController');
    Route::resource('task', 'TaskController');


    Route::group(['prefix' => 'datatable', 'as' => 'dtable.'], function () {
        Route::get('/project', [
            'uses' => 'ProjectController@datatable',
            'as' => 'project',
        ]);

        Route::get('/task', [
            'uses' => 'TaskController@datatable',
            'as' => 'task',
        ]);

        Route::get('/user', [
            'uses' => 'UserController@datatable',
            'as' => 'user',
        ]);
    });
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    public function project() {
        return $this->belongsTo(Project::class);
    }

    public function user() {
        return $this->project->user();
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Models\Task;
use App\Models\User;
use App\Notifications\TaskAssignedNotification;
use Carbon\Carbon;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    public function datatable(Request $request) {
        $model = Task::where([
            'project_id' => $request->project_id,
            'status' => $request->status,
        ]);

        $dTable = DataTables()->of($model)
        ->addIndexColumn()
        ->editColumn('created_at', function ($task) {
            return $task->created_at ? $task->created_at->format('d/M/Y') : '';
        });

        return $dTable->toJson();
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        $projectId = request()->query('project_id');
        $p = Project::findOrFail($projectId);
        $data['project'] = $p;
        if (empty($projectId))
            abort(403, 'Parameter project_id is missing ');

        $data['users'] = User::all();

        return view('task.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'project_id' => 'required|exists:projects,id',
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'assign_to' => 'required|exists:users,id',
            'deadline' => 'required|date',
            'status' => 'required|in:todo,onprogress,done',
        ]);

        $dl = \Carbon\Carbon::createFromFormat('m/d/Y g:i A', $request->deadline)->format('Y-m-d H:i:s');

        $task = new Task();
        $task->project_id = $request->project_id;
        $task->title = $request->title;
        $task->description = $request->description;
        $task->assigned_to = $request->assign_to;
        $task->progress = 0;
        $task->deadline = $dl;
        $task->status = $request->status;

        $task->save();
        $user = User::find($request->assign_to);
        $user->notify(new TaskAssignedNotification($task));

        return redirect()->route('backsite.task.show', ['task' => $request->project_id, 'type' => $request->status])->with('success', 'Task created successfully!');
    }


    /**
     * Display the specified resource.
     */
    public function show(int $projectId)
    {
        $p = Project::with(['tasks'])->whereId($projectId)->firstOrFail();
        $data['project'] = $p;

        if (!empty(session('error_msg')))
            Alert::error('Failed !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        return view('task.index', $data);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
        $task = Task::findOrFail($id);

        $user = auth()->user();
        $notification = $user->notifications()->find($id);
        if ($notification) {
            $notification->markAsRead();
        }
    
        
        $data['task'] = $task;
        $data['project'] = Project::find($task->project_id);
        $data['users'] = User::all();
        $dateTime = Carbon::createFromFormat('Y-m-d H:i:s', $task->deadline);

        $formattedDateTime = $dateTime->format('m/d/Y h:i A');
        $data['newDl'] = $formattedDateTime;

        return view('task.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $task = Task::findOrFail($id);

        $validatedData = $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'deadline' => 'required',
            'assign_to' => 'required|exists:users,id',
            'status' => 'required|in:todo,onprogress,done',
        ]);

        $task->title = $validatedData['title'];
        $task->description = $validatedData['description'];
        $task->deadline = Carbon::createFromFormat('m/d/Y h:i A', $validatedData['deadline'])->format('Y-m-d H:i:s');
        $task->assigned_to = $validatedData['assign_to'];
        $task->status = $validatedData['status'];

        $task->save();

        return redirect()->route('backsite.task.show', ['task' => $request->project_id, 'type' => $request->status])->with('success', 'Task updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        try {
            $task = Task::find($id);
            $task->delete();

        } catch (\Exception $e) {
            return redirect()->route('backsite.task.show', ['task' => request()->project_id, 'type' => request()->status])->with('error_msg', 'Delete Task failed.');
        }
        return redirect()->route('backsite.task.show', ['task' => request()->project_id, 'type' => request()->status])->with('success', 'Task deleted successfully.');
    }
}

resources/views/task/create.blade.php
@extends('layouts.app-master')

@section('menuProject', 'active')

@section('style')
<style>
    .radio label {
        cursor: pointer;
        padding-left: 35px;
        position: relative;
        color: black;
    }
    .help-block {
        color: red;
    }
</style>
@endsection

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" action="{{ route('backsite.task.store') }}" class="form-horizontal">
                        @csrf
                        <input type="hidden" value="{{ request()->query('project_id') }}" name="project_id">

                        <div class="card-header card-header-text" data-background-color="rose">
                            <h4 class="card-title">Create Task For {{ $project->title }}</h4>
                        </div>
                        <div class="card-content">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Title</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating {{ $errors->has('title') ? 'has-error' : '' }}">
                                        <input type="text" class="form-control" name="title" placeholder="Title" value="{{ old('title') }}">
                                        @if ($errors->has('title'))
                                            <span class="help-block">{{ $errors->first('title') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Description</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating {{ $errors->has('description') ? 'has-error' : '' }}">
                                        <textarea class="form-control" placeholder="Description" name="description">{{ old('description') }}</textarea>
                                        @if ($errors->has('description'))
                                            <span class="help-block">{{ $errors->first('description') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Deadline</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating {{ $errors->has('deadline') ? 'has-error' : '' }}">
                                        <input type="text" class="form-control datetimepicker" name="deadline" value="{{ old('deadline', date('m/d/Y')) }}"/>
                                        @if ($errors->has('deadline'))
                                            <span class="help-block">{{ $errors->first('deadline') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Assign To</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating {{ $errors->has('assign_to') ? 'has-error' : '' }}">
                                        <select class="selectpicker" data-style="btn btn-primary btn-round" title="Single Select" data-size="7" name="assign_to">
                                            <option disabled selected>Choose user</option>
                                            @forelse ($users as $u)
                                            <option value="{{ $u->id }}" {{ old('assign_to') == $u->id ? 'selected' : '' }}>{{ $u->name }}</option>
                                            @empty
                                            <p>No users available</p>
                                            @endforelse
                                        </select>
                                        @if ($errors->has('assign_to'))
                                            <span class="help-block">{{ $errors->first('assign_to') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Status</label>
                                <div class="col-sm-10">
                                    <div class="col-sm-5 checkbox-radios">
                                        @foreach(['todo' => 'Todo', 'onprogress' => 'Onprogress', 'done' => 'Done'] as $value => $label)
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="status" value="{{ $value }}" {{ old('status') == $value ? 'checked' : '' }}> {{ $label }}
                                            </label>
                                        </div>
                                        @endforeach
                                        @if ($errors->has('status'))
                                            <span class="help-block">{{ $errors->first('status') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-2">
                                    <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $('.datetimepicker').datetimepicker({
        icons: {
            time: "fa fa-clock-o",
            date: "fa fa-calendar",
            up: "fa fa-chevron-up",
            down: "fa fa-chevron-down",
            previous: 'fa fa-chevron-left',
            next: 'fa fa-chevron-right',
            today: 'fa fa-screenshot',
            clear: 'fa fa-trash',
            close: 'fa fa-remove',
            inline: true
        }
    });
</script>
@endsection

resources/views/task/edit.blade.php
@extends('layouts.app-master')

@section('menuProject', 'active')

@section('style')
<style>
    .radio label {
        cursor: pointer;
        padding-left: 35px;
        position: relative;
        color: black;
    }
    .help-block {
        color: red;
    }
</style>
@endsection

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" action="{{ route('backsite.task.update', $task->id) }}" class="form-horizontal">
                        @csrf
                        @method('PUT')
                        <input type="hidden" value="{{ $project->id }}" name="project_id">

                        <div class="card-header card-header-text" data-background-color="rose">
                            <h4 class="card-title">Update Task {{ $task->title }}</h4>
                        </div>
                        <div class="card-content">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Title</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating {{ $errors->has('title') ? 'has-error' : '' }}">
                                        <input type="text" class="form-control" name="title" placeholder="Title" value="{{ $task->title }}">
                                        @if ($errors->has('title'))
                                            <span class="help-block">{{ $errors->first('title') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Description</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating {{ $errors->has('description') ? 'has-error' : '' }}">
                                        <textarea class="form-control" placeholder="Description" name="description">{{ $task->description }}</textarea>
                                        @if ($errors->has('description'))
                                            <span class="help-block">{{ $errors->first('description') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Deadline</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating {{ $errors->has('deadline') ? 'has-error' : '' }}">
                                        <input type="text" class="form-control datetimepicker" name="deadline" value="{{ $newDl }}"/>
                                        @if ($errors->has('deadline'))
                                            <span class="help-block">{{ $errors->first('deadline') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Assign To</label>
                                <div class="col-sm-10">
                                    <div class="form-group label-floating {{ $errors->has('assign_to') ? 'has-error' : '' }}">
                                        <select class="selectpicker" data-style="btn btn-primary btn-round" title="Single Select" data-size="7" name="assign_to">
                                            <option disabled selected>Choose user</option>
                                            @forelse ($users as $u)
                                            <option value="{{ $u->id }}" {{ $task->assigned_to == $u->id ? 'selected' : '' }}>{{ $u->name }}</option>
                                            @empty
                                            <p>No users available</p>
                                            @endforelse
                                        </select>
                                        @if ($errors->has('assign_to'))
                                            <span class="help-block">{{ $errors->first('assign_to') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">Status</label>
                                <div class="col-sm-10">
                                    <div class="col-sm-5 checkbox-radios">
                                        @foreach(['todo' => 'Todo', 'onprogress' => 'Onprogress', 'done' => 'Done'] as $value => $label)
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="status" value="{{ $value }}" {{ $task->status == $value ? 'checked' : '' }}> {{ $label }}
                                            </label>
                                        </div>
                                        @endforeach
                                        @if ($errors->has('status'))
                                            <span class="help-block">{{ $errors->first('status') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-4">
                                    <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                                    <a href="{{ route('backsite.task.show', ['task' => $task->project_id, 'type' => $task->status]) }}" class="btn btn-fill btn-info">Back</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $('.datetimepicker').datetimepicker({
        icons: {
            time: "fa fa-clock-o",
            date: "fa fa-calendar",
            up: "fa fa-chevron-up",
            down: "fa fa-chevron-down",
            previous: 'fa fa-chevron-left',
            next: 'fa fa-chevron-right',
            today: 'fa fa-screenshot',
            clear: 'fa fa-trash',
            close: 'fa fa-remove',
            inline: true
        }
    });
</script>
@endsection

resources/views/task/index.blade.php
@extends('layouts.app-master')
@section('menuProject', 'active')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <a href="{{ route('backsite.task.create') }}?project_id={{ $project->id }}" class="card-header card-header-icon" data-background-color="purple">
                        <i class="material-icons">add</i>
                    </a>
                    <div class="card-content">
                        <h4 class="card-title">Tasks of {{ $project->title }}</h4>
                        <ul class="nav nav-pills nav-pills-warning">
                            <li class="{{ request()->query('type') == 'todo' ? 'active' : '' }}">
                                <a href="{{ route('backsite.task.show', $project->id) }}?type=todo">To Do</a>
                            </li>
                            <li class="{{ request()->query('type') == 'onprogress' ? 'active' : '' }}">
                                <a href="{{ route('backsite.task.show', $project->id) }}?type=onprogress">Onprogress</a>
                            </li>
                            <li class="{{ request()->query('type') == 'done' ? 'active' : '' }}">
                                <a href="{{ route('backsite.task.show', $project->id) }}?type=done">Done</a>
                            </li>
                        </ul>
                        <div class="material-datatables">
                            <table id="dtable" class="dtable table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Title</th>
                                        <th>Description</th>
                                        <th>Assigned To</th>
                                        <th>Deadline</th>
                                        <th class="disabled-sorting text-right" width="20%">Actions</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>No</th>
                                        <th>Title</th>
                                        <th>Description</th>
                                        <th>Assigned To</th>
                                        <th>Deadline</th>
                                        <th class="disabled-sorting text-right">Actions</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- end content-->
                </div>
                <!--  end card  -->
            </div>
            <!-- end col-md-12 -->
        </div>
        <!-- end row -->
    </div>
</div>
@endsection

@section('script')
<script>
    getDatatable()

    function getDatatable() {
        /*Datatable*/
        $('.dtable').DataTable().destroy();
        $('.dtable').DataTable({
            serverSide: true,
            processing: true,
            lengthChange: false,
            ajax: {
                type: 'GET',
                url: "{{ route('backsite.dtable.task') }}",
                data: {
                    _token: "{{ csrf_token() }}",
                    project_id: "{{ $project->id }}",
                    status: "{{ request()->query('type') }}",
                }
            },
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'title',
                    name: 'title'
                },
                {
                    data: 'description',
                    name: 'description'
                },
                {
                    data: 'created_at',
                    name: 'created_at'
                },
                {
                    data: 'deadline',
                    name: 'deadline'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false,
                    render: function(data, type, row) {
                        return ` 
                        <form action="${route('backsite.task.destroy', {
                            id: row.id,
                        })}" method="POST" id="form_${row.id}">
                            @csrf
                            <input type="hidden" name="_method" value="delete">
                            <input type="hidden" name="project_id" value="{{ $project->id }}">
                            <input type="hidden" name="status" value="{{ request()->query('type') }}">
                            <a type="button" rel="tooltip" class="btn btn-sm btn-success btn-round" data-original-title="" title="" href="${route('backsite.task.edit', {
                                id: row.id
                            })}">
                                <i class="material-icons">edit</i>
                            </a>

                            <button type="submit" rel="tooltip" class="btn btn-sm btn-danger btn-round btn_delete" id="${row.id}" data-original-title="" title="">
                                <i class="material-icons">delete</i>
                            </button>
                        </form>
                        `
                    }
                },
            ]
        })
    }

    $(document).on('click', '.btn_delete', function(e) {
        e.preventDefault()

        Swal.fire({
            icon: 'warning',
            title: 'Are You Sure ?',
            text: "Are you sure to delete this item!",
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it !'
        }).then((result) => {
            if (result.isConfirmed) {
                let id = $(this).attr('id')
                $("#form_" + id).submit()
            }
        });
    })
</script>
@endsection